Feature | flujo de login y registro | DEX-002 | patricia.corona
patycorona/Doge-Dex pull request #2
Opened 2023-08-16 17:29 UTC by patycorona

<em><B> LOGIN Y REGISTRO USUARIO </em></B>
Desarrollo de parte gráfica y programación en capas.

https://github.com/patycorona/Doge-Dex/assets/65816817/6e4c9030-35c3-45de-9549-614a3c69ef1c

https://github.com/patycorona/Doge-Dex/assets/65816817/622d7b3c-5522-4f67-83de-d0672df7ea19

2023-08-17 01:22 UTC, mleyvar requested changes

2023-08-17 01:22 UTC, mleyvar commented on app/src/main/java/com/example/dogedex/ui/auth/views/LoginFragment.kt
> +            (activity as LoginActivity)
aqui no es conveniente llamar al viewmodel y despues cambiar de pantalla,  recuerda que eso lo controlamos con livedata o courutinas en los observadores y ahi hacemos el cambio de pantalla, aqui se puede perder el proceso cuando cambies de pantalla

2023-08-17 01:22 UTC, mleyvar commented on app/src/main/java/com/example/dogedex/ui/auth/views/SingUpFragment.kt
> +            (activity as LoginActivity)
igual aqui

2023-08-18 14:09 UTC, patycorona commented on app/src/main/java/com/example/dogedex/ui/auth/views/LoginFragment.kt
> +            (activity as LoginActivity)
un callback de un observador, lo que hago antes de cambiar de pantalla es llenar un objeto que le voy a pasar como parámetro eso es todo, no mando llamar al viewmodel.

2023-08-18 14:10 UTC, patycorona commented on app/src/main/java/com/example/dogedex/ui/auth/views/SingUpFragment.kt
> +            (activity as LoginActivity)
lo mismo aquí.

2023-08-18 15:28 UTC, mleyvar approved these changes

2023-08-18 15:28 UTC, mleyvar commented on app/src/main/java/com/example/dogedex/ui/auth/views/LoginFragment.kt
> +            (activity as LoginActivity)
es correcto paty. good

2023-08-18 15:47 UTC, merged