Feature | ordenar lista de Dogs y filtrar listOfTheDogsByUser | DEX-003 | patricia.corona
patycorona/Doge-Dex pull request #3
Opened 2023-08-19 04:40 UTC by patycorona

<em>Cuando se preciona un item de la lista de Dogs por unos segundos se agrega a las lista de usuario.

https://github.com/patycorona/Doge-Dex/assets/65816817/2d61ec46-7f08-48c3-abf1-820be53b76c7

Mostarmos en el home la consulta de la lista de Dogs por usuario y ordena por el indice,
![image](https://github.com/patycorona/Doge-Dex/assets/65816817/7257d3df-d9d6-46e3-87e6-b32d297711c2)

2023-08-19 20:33 UTC, mleyvar requested changes

2023-08-19 20:33 UTC, mleyvar commented on app/src/main/java/com/example/dogedex/data/model/response/ApiServiceInterceptor.kt
> +                throw RuntimeException("Need  to be authentication to perform")
constantres aqui

2023-08-19 20:33 UTC, mleyvar commented on app/src/main/java/com/example/dogedex/data/model/response/ApiServiceInterceptor.kt
> +                requestBuilder.addHeader("AUTH-TOKEN", sessionToken!!)
igual

2023-08-19 20:33 UTC, mleyvar commented on app/src/main/java/com/example/dogedex/data/repository/DogRepositoryImpl.kt
> +            if (id != null) DefaultResponse("Dog Added to list", true,)
igual

2023-08-19 20:33 UTC, mleyvar commented on app/src/main/java/com/example/dogedex/data/repository/DogRepositoryImpl.kt
> +                DogModel(it.id,it.index, "","","","",
constante para empty

2023-08-19 22:22 UTC, patycorona commented on app/src/main/java/com/example/dogedex/data/model/response/ApiServiceInterceptor.kt
> +                throw RuntimeException("Need  to be authentication to perform")
Listo, ya esta en constantes

2023-08-19 22:22 UTC, patycorona commented on app/src/main/java/com/example/dogedex/data/model/response/ApiServiceInterceptor.kt
> +                requestBuilder.addHeader("AUTH-TOKEN", sessionToken!!)
igual aqui.

2023-08-19 22:23 UTC, patycorona commented on app/src/main/java/com/example/dogedex/data/repository/DogRepositoryImpl.kt
> +            if (id != null) DefaultResponse("Dog Added to list", true,)
Listo, ya en constantes.

2023-08-19 22:23 UTC, patycorona commented on app/src/main/java/com/example/dogedex/data/repository/DogRepositoryImpl.kt
> +                DogModel(it.id,it.index, "","","","",
Listo.

2023-08-20 00:33 UTC, mleyvar requested changes

2023-08-20 00:33 UTC, mleyvar commented on app/src/main/java/com/example/dogedex/domain/model/DogModel.kt
> +            1
magic number- constant

2023-08-20 00:33 UTC, mleyvar commented on app/src/main/java/com/example/dogedex/domain/model/DogModel.kt
> +            -1
the same

2023-08-20 00:44 UTC, patycorona commented on app/src/main/java/com/example/dogedex/domain/model/DogModel.kt
> +            1
listo

2023-08-20 00:44 UTC, patycorona commented on app/src/main/java/com/example/dogedex/domain/model/DogModel.kt
> +            -1
listo

2023-08-20 01:17 UTC, mleyvar approved these changes

2023-08-20 03:26 UTC, merged